### ISSUE TITLE
Enhancement: category and pagination

### ISSUE THREAD

**Issue by cinker** [sissbruecker/linkding#11]
Firstly I want to thank you for this wonderful bookmark manager. It is just what I'm looking for.

Two suggestions you may consider:
1). Pagination. If someone happens to manage many bookmarks, that would be diserable.
2). Category. In addition to tags, category is still an effective way to organise bookmarks.

Thanks again!

**Comment by sissbruecker** [comment]
Hello Cinker,

1. I understand your intention. However the idea for finding a bookmark again is that you use the search function to look for a bookmark, rather than looking for it manually by clicking through lots of pages. What would be the use-case for selecting a specific page of bookmarks?
2. I don't understand this one - for me a tag is pretty much a category. Do you have an example, like a picture from an existing application where you saw both concepts combined?

**Comment by gokomer** [comment]
Hi @sissbruecker 

I'm in favor of pagination. I don't remember everything I bookmarked to search for them. Sometimes I go through my bookmarks page by page to see what I've bookmarked.

**Comment by sissbruecker** [comment]
OK, will consider adding pagination.
