### ISSUE TITLE
Add support for custom base URL to play nice with reverse proxy

### ISSUE THREAD

**Issue by wallace11** [sissbruecker/linkding#127]
I've been trying to set a reverse proxy for linkding for hours.
I'm using [SWAG](https://docs.linuxserver.io/general/swag) which includes a Let's Encrypt integration and an NGINX server with a relatively easy to configure templates.

This setting should've been enough:

```config
location /bm/ {
	include /config/nginx/proxy.conf;
	resolver 127.0.0.11 valid=30s;
	set $upstream_app linkding;
	set $upstream_port 9090;
	set $upstream_proto http;
	proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}
```
**Note:** `linkding` is the container name, and I've been trying to set `www.mysite.com/bm` as the access URL.

No matter what I'm doing, the internal linkding server is getting `/bm/` which it doesn't know how to process:

```
[pid: 12|app: 0|req: 1/1] 172.22.0.4 () {48 vars in 947 bytes} [Tue May 18 10:46:08 2021] GET /bm/ => generated 77 bytes in 255 msecs (HTTP/1.1 404) 5 headers in 153 bytes (1 switches on core 0)
```

Maybe there's a way to circumvent that, but I see that most self hosted apps allow for setting a base URL (which in my case would be `/bm/`) to tell the app where the start point is.

**Comment by sissbruecker** [comment]
While that would be a nice to have feature, it seems you could work around your issue if you would use a sub-domain instead of a folder: `bm.mysite.com`

Another option are URL rewrites I think, but I don't have experience with that.

**Comment by hollispotter** [comment]
Hi, I ran into the same issue. I've forked the repo and fixed it for my own use. You can see the changes here:

https://github.com/hollispotter/linkding/commit/6ac7d46e5112055357a3116409d1ad9767424dbf

If you would like, I can send this as a pull request. It's a fairly minor change, but I am not a Python/Django developer by trade and consider this a bit of a hack.

**Comment by sissbruecker** [comment]
@hollispotter Looks like a good start, but it would need some improvements:
- instead of duplicating the env variable everywhere introduce a setting that is then reused
- the change to the url patterns assumes that a base url will be present and prepends a `/` to the paths even if there is no base url
- this needs some way of testing to verify that the app works with/without base URL, easiest is probably to run the test suite with the env variable set, and having a test case that generates a few URLs to check if the setting is respected
- the option would need to be documented in `options.md` so that it's discoverable

If you are willing to improve on those points, then feel free to open a PR.

**Comment by qiaohao9** [comment]
Is there any follow-up here?

**Comment by es9o** [comment]
I'm also interested in a base URL option and am confirming that I haven't been able to find any combination of rewrite rules for Nginx that accommodates it in linkding's current implementation.

**Comment by gingerbeardman** [comment]
I'm using it on Synology with a subdomain and reverse proxy and all is well.
