### ISSUE TITLE
archive.org integration should be configurable (opt-in)

### ISSUE THREAD

**Issue by fs111** [sissbruecker/linkding#157]
With the new release linkding sends all urls to archive.org. While that may be useful to some it is a privacy problem. I am self-hosting my bookmarks to limit the amount of services that know about my bookmarks. With the new feature that is no longer the case.

I assume setting `LD_DISABLE_BACKGROUND_TASKS` to `True` will help, but I that seems broader than just archive.org integration.

Side note: Using a positive term ("Enable") and setting it to `False` is a lot more obvious to most humans, than having a "Disable" flag.

**Comment by sissbruecker** [comment]
Thanks for bringing this up, and I understand your concern. However at this time I would like to keep this feature as opt-out, as I think that the majority of users would expect this feature to work OOTB. I'm open to reconsider this if there is enough data to prove that the majority of users would like to have this disabled by default.

I also think that there is a difference in terms of privacy concerns with an online service where you have an account with bookmarks that is easily accessible by said service, vs. a self-hosted service that would allow to correlate your IP address to your bookmarks, assuming that the IA has an interest in doing this. Again, not saying that your concerns aren't valid, just stating that there are different levels of concerns when talking about self-hosting.

In the meantime you can safely use the `LD_DISABLE_BACKGROUND_TASKS` option to turn off the feature. The option doesn't do anything else at the moment. If another feature comes up that would require background tasks, then we can consider adding a new option just for turning off the snapshot creation.

**Comment by sissbruecker** [comment]
Another alternative I can think of is adding a user setting for this. Then the issue is discoverable and explainable in the UI, and you could easily turn it off without messing with Docker options.

**Comment by M4NH3X** [comment]
Wanted to suggest the same feature but luckily found the issue here. Yes please, a settings in the web-ui itself would be really handy.

I just didn't like the fact that it's enabled by default without giving an opt out option. It was my mistake to not read main readme page carefully. I will re-deploy with `LD_DISABLE_BACKGROUND_TASKS` as the workaround.

Lastly, love the ui and sleekness of this tool. Great work on that and appreciate the project. :+1:

**Comment by 917huB** [comment]
I’d like to see the ability to configure a link to a self hosted archivebox install to archive articles locally rather than on cloud.

**Comment by clach04** [comment]
A web-config option would obviously be great, but I personally consider opt-in as the the privacy/safety option.

Opt-out is definitely convenient but for privacy reasons (or for sites that are not available to IA) opt-out is not a great choice especially when this behavior is not clear. Thanks for making a runtime option so that this can be disabled :) I've just posted a PR to help with the later point, viz. make it clear that this archives by default and that it can be disabled.

**Comment by sissbruecker** [comment]
Thanks for all the feedback, I decided to go ahead with this, and make the feature opt-in. See #250 for more details.
