### ISSUE TITLE
Add bookmark sort option

### ISSUE THREAD

**Issue by molejado** [sissbruecker/linkding#188]
Is it possible to implement sorting bookmarks not only by time, but also manually? Some bookmarks are prioritized for a long time and I would not like to see them at the end, one of the options is to set the date in the future, but in this case the internal perfectionist rebelles)
Thanks for your hard work.

**Comment by deanord** [comment]
Alternatively, can the bookmarks sort alphabetically instead of date added (?)

**Comment by sissbruecker** [comment]
@molejado 

Manual sorting would add too much complexity that very few people would make use of IMO. Prioritizing bookmarks sounds interesting, I could imagine a something for marking bookmarks as favorites and then provide a quick way to access them. On the other hand you can pretty much do that already: add a tag `favorite` to all your regularily used bookmarks, and then filter for that tag, or even bookmark the search result page in the browser (e.g. `https://linkding.domain.com/bookmarks?q=%23favorite`).

@deanord 

What would be the use case for that? It kind of sounds like you want this for maintaining your bookmarks. Note that this feature exists in the admin UI. Go to Admin from Settings, select Bookmarks, then click on the respective column header to sort the table.

**Comment by deanord** [comment]
@sissbruecker , thanks for the reply.
No, the alphabetical sort is not for maintaining the bookmarks, it's for simple navigation.
I use tags extensively (of course), but some tags return a page or more of results.  I need to scan the entire list (which though by added date, may as well be in a randomized order).  Intuitively, one assumes the bookmarks are listed alphabetically--but they are not and there's no option to do this.  As a result, I find that I stop using tags altogether, which minimizes what I consider linkding's best feature.

**Comment by sissbruecker** [comment]
OK thanks for clarifying, sounds like alphabetical sorting could be useful.

**Comment by sissbruecker** [comment]
From #347:

> As I currently see, the default sorting is the newly created ones will be listed on the top.
> I often update the older link to keep it up to date. I usually done this when I was reading manga on Mangaplus or watching anime in Bilibili. As more newer bookmarks are added, the older ones will pushed behind further and further. This makes navigating to it quite annoying, especially for often updated and visited links.
> Having sort option will help a lot for this kind of use. I think for a starter, having an option to sort by create date (the current default), update date, and title should be enough.

**Comment by zaryth** [comment]
I support the idea of ​​sorting by name/title! Thank you!

**Comment by tategriffin** [comment]
I'd like to see this feature as well. It would be great if the default sorting was by date _when no tag is selected_, and the default sorting was by title _when 1 or more tags are selected_.

**Comment by JeffCrum1** [comment]
I just started using this.  I'd love an alphabetic sort based on Title.

**Comment by JeffCrum1** [comment]
I'd love to see a sort by title.

I'd also love to see selection by (user=user or shared=yes).

So, I see all of my bookmarks and all of the ones shared by my wife and all the ones shared by my kid in one page. Basically, everything I should be able to see in one place.

**Comment by mikezila** [comment]
I'd like to +1 to sorting by title alphabetically as a configurable option. Alphabetically is just the intuitive default way to assume any list is sorted, and gives me a good idea of how far I have to scroll/page to find the bookmark I'm after. Ideally I want to avoid having to engage the search box to find a bookmark except as a last resort, because if I'm searching linkding for a bookmark chances are I could have skipped going to linkding altogether and just searched in my browser to find it.

I personally use linkding as my one and only place to keep bookmarks so that I don't have to worry about importing/setting up any browser I happen to be using, and it's kind of a bummer there aren't more tools to control how my bookmarks are presented. Right now I'm semi working around the issue by using more specific tags, or having multiple tags that boil down to being "favorites" lists.

Failing the ability to sort alphabetically, a "star" option may be helpful to pin important/frequent bookmarks to the top of a given tag. An option to perhaps sort bookmarks by visit frequency would also be nice. Just more/any sorting options would be better than the lack that we have now.

**Comment by cwschulz** [comment]
+1 for the ability to pin or star bookmarks

**Comment by ItsNoted** [comment]
I just came here to make a issue request for pinning links to the top but found this issue and decided to add my vote for pins. Especially helpful for those of us sharing public links.
