### ISSUE TITLE
Support for private bookmarks

### ISSUE THREAD

**Issue by gingerbeardman** [sissbruecker/linkding#204]
On pinboard I marked a bunch of bookmarks as private.

on the link in the HTML it's shown as `PRIVATE="1"`, eg.

`<A HREF="https://secret.com/" ADD_DATE="1234567890" PRIVATE="1" TOREAD="0" TAGS="">`

it would be good if that metadata was imported into Linkding and surfaced in the user interface.

Thanks!

**Comment by gingerbeardman** [comment]
It's interesting that exporting bookmarks has the PRIVATE flag set to 0 on all links.

I confirmed that the PRIVATE flag is not present in the database

**Comment by jacobian** [comment]
This is a feature I'm interested as well. @sissbruecker I'd be happy to put together a PR if it's a feature you want.

**Comment by sissbruecker** [comment]
What would that feature be?

**Comment by jacobian** [comment]
Essentially a `private` flag (and the associated import stuff). I know you've said that public bookmarks aren't something you want for this app (#70), which, fair, but having a some sort of a flag would folks (including me) who want to build their own sort of public bookmarks view on top of the API something to hook into.

**Comment by clach04** [comment]
Based on the current model, I think mapping to a tag might be the best option for an importer that looks for private attribute. E.g. private=0 could map to a "public" tag.

**Comment by gingerbeardman** [comment]
@clach04 the standard method for previous bookmarks systems (since delicious) is for all bookmarks to be public unless specifically marked as private. To do it the other way would be strange, but I guess it would work. I can see your point with this system intended to be personal bookmarks.

Regardless, importing bookmarks with private flag is essential.

**Comment by sissbruecker** [comment]
> Essentially a `private` flag (and the associated import stuff). I know you've said that public bookmarks aren't something you want for this app (#70), which, fair, but having a some sort of a flag would folks (including me) who want to build their own sort of public bookmarks view on top of the API something to hook into.

@jacobian As mentioned in the linked ticket, you could just use a tag for this? I don't see any point in adding a flag that has no functionality in the application itself, especially if we consider surfacing that in the UI. It would just confuse people, or create expectations about features that do not exist, such as bookmarks somehow being private or public.

**Comment by gingerbeardman** [comment]
Tag sounds fine, as long as it was set on import and mapped back to private on export?

**Comment by sissbruecker** [comment]
Seems this didn't go anywhere, I'm closing this for now. Adding support for public bookmarks could be an alternative feature request that would add an actual feature.

**Comment by joshdick** [comment]
+1 for this issue.

I get that Linkding is meant for personal use and thus currently has no concept of private vs public bookmarks.

However, I do have some Pinboard bookmarks marked as private, and it would be nice to preserve that metadata when importing into/exporting from Linkding, even if I am the only one that can ever see any bookmarks in my installation. Since other bookmarking tools do understand and use that metadata, it's unfortunate that Linkding strips it.

I think adding a private bookmarks feature to Linkding should be less about whether Linkding itself has any notion of public vs. private bookmarks, and more about being compatible with other bookmarking tools that use the same Netscape bookmarks format.

> It would just confuse people, or create expectations about features that do not exist, such as bookmarks somehow being private or public.

I totally understand this concern, but I'm curious what the `PRIVATE` attribute of the Netscape bookmarks format was originally used for, or if it was ever part of or understood by any web browser at all. Like Linkding, browser applications obviously don't have a notion of public bookmarks. Did any browser ever do something like locally password-protect private bookmarks? Was `PRIVATE` just arbitrarily added to the format by something like del.icio.us many years back?

Short of adding first-class support for public bookmarks to Linkding, and assuming the confusion issue is surmountable, I was picturing that a minimal "private" feature could work like this:
* The importer/exporter both understand and include user-specified values for `PRIVATE`, respectively.
* Bookmarks could be marked "private" via a "private" checkbox on the add/edit bookmark form.
* Bookmarks marked "private" would have a simple visual distinction on the corresponding bookmark listing, something a grey background with a lock icon in a corner.

**Comment by gingerbeardman** [comment]
Circling back to this issue.

I don't even want to share my bookmarks, I just want to flag bookmarks as "sensitive" like for my personal accounts, questionable content, and so on.

**Comment by gingerbeardman** [comment]
OK, so I see a lot of support for Shared bookmarks was added in Aug 2022
https://github.com/sissbruecker/linkding/commit/fec966f6872ca6f2d8564bf753e7d4d478207b70

my thoughts
- import still seems to strip private flag?
- there is no way to set shared/not through linkding web interface
- shared/not is not displayed in the list

@sissbruecker would you accept pull requests for any of these? happy to discuss so we are on the same page before staring any work on it.

Cheers!
