### ISSUE TITLE
Add Lotus Notes links

### ISSUE THREAD

**Issue by clemone543** [sissbruecker/linkding#22]
Hello,

I am trying to setup linkding to use it with Lotus Notes.

I want to add Lotus Notes Document links as bookmarks.
Unfortunately its not possible.

A notes url/link looks like this:
notes://NOTESSERVER.SUBDMAIN.DOMAIN.COM/C12H9BF2F0261BDA/7B18866DH/THGUJZC1257D330032D158/0807E72E8A1D1B52C12585G/HFZ&RUZG

If you open this link, it redirects you to the document in Lotus Notes.
Would that be possible to add?

**Comment by sissbruecker** [comment]
@timohzbs So the issue is that the form's URL validation fails when you try to add a bookmark with that URL?

It should be possible to implement a custom URL field with a custom validator. Maybe I'll take a look at this at some point, but unless there are more users having issues like this I see this as low priority.

**Comment by sissbruecker** [comment]
As part of #36 I added an option to completely disable URL validation. I consider this solved as well.
