### ISSUE TITLE
Enhancement: detect duplicates at entry time

### ISSUE THREAD

**Issue by t-jones** [sissbruecker/linkding#23]
Thanks for this great app.  Perfect for managing a bunch of bookmarks.

What do you think about a warning/message when trying to bookmark a page that's already bookmarked?  If that sounds good, give me a couple pointers and I'll give you a PR.

**Comment by ashadulhoque** [comment]
For quick fix replacing line 32 of bookmarks/models.py from 'url = models.URLField()' to 'url = models.URLField(unique=True)' will prevent duplicate urls from inserting into the database.This is what I am doing right now.

Ideally, instead of trying to insert into database the app should update existing record in case of duplicate urls or even better display existing fields and save updates if any.

**Comment by sissbruecker** [comment]
Added some handling for this. The form will now check (from client-side, after entering the URL) if the URL is already bookmarked and then how a hint below the input:

![Bildschirmfoto 2020-09-13 um 08 38 08](https://user-images.githubusercontent.com/357820/93012116-c9a62180-f59d-11ea-9d2e-560838c35d35.png)

The hint provides the option to edit the original bookmark. 

If the form is saved regardless, then the existing bookmark is updated instead of creating a new one.

**Comment by vindevil** [comment]
Is it possible showing duplicate status on chrome extension button by different color?
