### ISSUE TITLE
API for app development

### ISSUE THREAD

**Issue by gokomer** [sissbruecker/linkding#24]
Hello,

Does linkding have API for developing browser extensions, desktop application etc. ?

**Comment by sissbruecker** [comment]
Currently not, but I see value in this. The API itself would probably not be too complicated since there are some nice OOTB REST solutions for Django. But there are some complex aspects to take care of, especially authentication. I figure the app would need to allow for authentication tokens and provide means to generate / display them in the UI. 

I'll leave this open, maybe I'll get to it some day.

**Comment by sissbruecker** [comment]
I added a basic REST API for managing bookmarks and tags. The docs can be found [here](https://github.com/sissbruecker/linkding/blob/master/API.md).

There's room for improvement, e.g. adding filter parameters to the bookmarks endpoint. I'll extend the API if there is demand for a specific use-case.
