### ISSUE TITLE
Add links directly to archive

### ISSUE THREAD

**Issue by ahuse** [sissbruecker/linkding#243]
I really would like to use `linkding` as a selfhosted alternative to [pinboard.in](https://pinboard.in/). But one minor missing feature still holds me back.

I use the "read later"-feature of pinboard to distinguish between articles/websites i want to read at a later time and articles/websites i just want to save (with tags). In linkding the normal view of links would be my "read-later"-list and the archive would be the list of links i just want to safe.

As is see it, it is currently not possible to add links directly to the archive. Would be great, if there is an "add to archive"-option (checkbox) in the bookmarklet-menu or second bookmarklet for adding links to the archive directly.

**Comment by bachya** [comment]
I assume this would be the case, but the API should also support sending bookmarks directly to the archive.

**Comment by ahuse** [comment]
Yes, I wrote a small iOS-Shortcuts-Script for adding links to the archive. It works, but would be nice to do the direct archive with a bookmarklet aswell.

**Comment by kencx** [comment]
Adding bookmarks directly to archive is now supported in the API with #268. 

Just include `is_archived: true` in the payload to `/api/bookmarks/`.

**Comment by ahuse** [comment]
This is great. I just updated my iOS-shortcut and it works as expected, plus the shortcut is less complex now.

Only thing missing for me is an option to archive for the bookmarklet.
Maybe a bookmarklet, which autocloses (without the need to hit `Save and close`), is also a good idea for a quick "read later".

**Comment by sissbruecker** [comment]
Instead of adding more workarounds to make the "use non-archived bookmarks as read it later list" work, I'd rather put in work on an actual read it later feature. I can see that being useful, and I did use that on Pinboard myself before I realized that I never catch up with all the stuff that I wanted to read.

I did some prototyping on this. The bookmark form would get an additional checkbox:

<img width="503" alt="Bildschirmfoto 2022-05-27 um 08 47 29" src="https://user-images.githubusercontent.com/357820/170646518-504ec434-cac7-4259-bf2b-a24943b286c3.png">

To make unread bookmarks discoverable, I would probably restructure the navigation to provide filter presets:

<img width="417" alt="Bildschirmfoto 2022-05-27 um 08 47 59" src="https://user-images.githubusercontent.com/357820/170646708-7e280800-2807-4d58-8f14-330683324ec3.png">

The unread bookmarks view would basically just be a special filter in the search query:

<img width="662" alt="Bildschirmfoto 2022-05-27 um 08 48 35" src="https://user-images.githubusercontent.com/357820/170646780-c38d5912-6a45-43db-af8f-6d4e001d5eb0.png">

And bookmarks marked as unread get an additional action to mark them as read:

<img width="423" alt="Bildschirmfoto 2022-05-27 um 08 49 11" src="https://user-images.githubusercontent.com/357820/170646835-506b2253-4b00-41d1-87a0-4920f9214b41.png">

You can give this a try using the [`sissbruecker/linkding:read-it-later`](https://hub.docker.com/layers/222206151/sissbruecker/linkding/read-it-later/images/sha256-d1647bf145ac26c4d30e8c0b79fce00411a5e04d2b3ab1a3e0d80739ad80d435?context=repo) Docker image. The image will not modify your database, the unread flag was actually there before, it just hadn't been utilized.
