### ISSUE TITLE
App for Android

### ISSUE THREAD

**Issue by LegendaryB** [sissbruecker/linkding#246]
Hey @sissbruecker ,

I'm using Firefox on Android and found no good way to add bookmarks to my linkding installation. So I decided to write a custom app in Flutter for Android. The browser now can share a URL to this app and the app forwards it to the linkding instance.

The app is nearly finished but I'm still testing a few things and doing some improvements. Just a few questions to finish it:
Can I use the linkding icon? And if yes do you have it in higher definition (1024x1024) for the app icon?

**Comment by sissbruecker** [comment]
Sure, you can use the icon. Added an SVG version below. You can open that with some graphics program and convert it to whatever you need. There's also the source Affinity Designer file [here](https://github.com/sissbruecker/linkding/blob/master/assets/logo.afdesign), if you have access to that program.

One thing I would like to ask is to clarify in the app store description (assuming you are going to publish it) that it is an unofficial app, otherwise people might end up here asking for support 🙂. Also feel free to open a PR for mentioning the app in the community section of the README: https://github.com/sissbruecker/linkding#community

![logo](https://user-images.githubusercontent.com/357820/167311054-85ba1f88-534f-4589-a17c-ce820d8cbe59.svg)

**Comment by LegendaryB** [comment]
Hey @sissbruecker,

ty for the fast response. I will probably only release it on F-Droid. But I will mention that its nothing official. Will ping you again when its finished. Maybe you want to try it out yourself 👍

**Comment by dahamsta** [comment]
Any progress on this? I'd love an app with 2x share targets:

1. **Fire and forget share** similar to the current _HTTP Shortcuts_ action.
2. **Popup share** similar to the Firefox extension, with the ability to choose tags at the very least.

Obviously it would be nice to browse, edit and delete links in the app too, and I assume that could basically be just a wrapper for the site, but share targets would be the primary use case for me. HTTP Shortcuts is a bit of a nasty hack.

I would be happy to contribute to a bounty for this app on [Bountysource](https://www.bountysource.com/) or similar.

**Comment by rounakdatta** [comment]
We can also track https://github.com/fibelatti/pinboard-kotlin/issues/107, Pinkt is a fantastic app, and if it starts supporting Linkding, that would be amazing!
