### ISSUE TITLE
Enhancement: let user configure to open links in same tab instead on a new window/tab

### ISSUE THREAD

**Issue by hirusi** [sissbruecker/linkding#27]
My use-case: I use my linkding site as the default new tab page. I would like to quickly search and open a link in the same tab.

Currently, clicking a link opens a new tab and I'm left with the new tab that I had opened with linkding, as well as the actual link I wanted to open in another new tab.

This actually involves two facets once a user configures these:

1. `autofocus` on the linkding search bar
2. update the target values on the linkding bookmark entries to open in current tab

**Comment by sissbruecker** [comment]
Seems reasonable, I'm going to take a stab at this at some point.

**Comment by Export33** [comment]
Adding an `autofocus` to the forminput is easily made and i l ike the idea.

Changing the default link opening could be impemented with #76 .

**Comment by sissbruecker** [comment]
Added a user profile setting for opening bookmarks either in a new page, or in the same page.

Decided against setting autofocus on the search box for now, as these two features are not necessary related. A recent addition (#161) allows to focus the search box by pressing <kbd>s</kbd>, as long as the page has focus, so there is a reasonable workaround.

With regards to the original request of using linkding as the new tab page, and focusing the search box, I'm having a bit trouble to understand how one would work with that setup. Usually in new tabs I want to trigger a web search, so I want to focus the browsers address bar, rather than an input in the new tab page. I found the idea interesting though, so I added an alternative to the linkding browser extension (https://github.com/sissbruecker/linkding-extension/pull/9). The extension now integrates with the address bar / omnibox, so that you can search for bookmarks stored in linkding from the address bar. To do so, enter `ld`, followed by <kbd>Space</kbd>, and then enter the search term. The address bar will now suggest bookmarks from linkding. The default suggestion will simply open linkding in the current tab, and trigger a search for the entered search term. Combined with the new setting introduced here that could be a good alternative.

The update is released for Firefox, Chrome is still pending.
