### ISSUE TITLE
Question / Feature Request - Possibility to set the Title of a Website trough HTTP GET (use it in a Bookmarklet)

### ISSUE THREAD

**Issue by serial-bug** [sissbruecker/linkding#292]
Hello there,

at the moment it seems that you only can set the URL trough a GET Request.
Example:

```
javascript: (function() {
var bookmarkUrl = window.location;
var applicationUrl = 'https://instance.name/bookmarks/new';
applicationUrl += '?url=' + encodeURIComponent(bookmarkUrl);
applicationUrl += '&auto_close';
window.open(applicationUrl);
})();
```

So, it would be great if it where possible to also set the website title trough a GET Request.
The code in a bookmarklet could be:

```
javascript: (function() {    
var bookmarkUrl = window.location;    
var applicationUrl = 'https://instance.name/bookmarks/new'; 
var bookmarkTitle = document.title;
applicationUrl += '?url=' + encodeURIComponent(bookmarkUrl); 
applicationUrl += '&title=' + encodeURIComponent(bookmarkTitle); 
applicationUrl += '&auto_close';
window.open(applicationUrl);
})();
```

If this where possible, the website title can be scrapped at the client and so the docker container in the backend dont have to be connected to the internet. (sure, waybackmachine archive and description wouldn work then but this is ok for me)

Thank you very much.

**Comment by sissbruecker** [comment]
Title, description, and website metadata are different fields in linkding. Entering a title does not prevent scraping website metadata, so this would require additional logic.

I'll close this in favor of https://github.com/sissbruecker/linkding/issues/118, which is also about providing the metadata from the client, rather than scraping it on the server.
