### ISSUE TITLE
Would be nice to batch mark items as read/unread

### ISSUE THREAD

**Issue by kzshantonu** [sissbruecker/linkding#308]
<img width="501" alt="brave_8xjdx9IFe0" src="https://user-images.githubusercontent.com/7745374/182007658-6cfecc01-85cb-4c75-a938-02fd6f4d76e3.png">

PS: love the new update

**Comment by sissbruecker** [comment]
Yeah that should be possible. I'd like to avoid dumping more actions into the bulk edit bar though, so I'm still thinking on how to do this. Maybe use a select element to pick the action, similar to how it works in the admin.

For now the admin panel has actions for marking bookmarks as read/unread, so that could be used as a workaround.

**Comment by michaelquigley** [comment]
Would like to upvote this feature. 👍
