### ISSUE TITLE
Comments for Links

### ISSUE THREAD

**Issue by tobru** [sissbruecker/linkding#327]
In addition to the "Description" field, it would be cool to have a new "Comments" field. I usually like to add a few notes or thoughts to a link, why I bookmarked a link for example, but leaving the description intact. For now, I'm using the description field, but feels semantically incorrect to do so, as I'm now mixing the description and my comments into the same field.

**Comment by michaelx** [comment]
Agreed. An additional field for comments/notes with Markdown support would be helpful.

**Comment by turkishmaid** [comment]
Supporting this enhancement request. Also the comments field should be well bigger than the current description. I use to add lots of info from the linked page in the description (for future quoting etc.), and the two lines turns out to be quite a Sehschlitz to the text in this case. This is even more annoying with iOS Safari which does not sow me the resize handle of the texture, so it's really only two lines.

**Comment by catusax** [comment]
i have made a commit witch add a comment filed, see https://github.com/catusax/linkding/commit/5795cc5ab7085be379a3ad5e85a2ec48744b584c
But it affects database table and Web UI. I think it's a big decision, should i open a pull request? @sissbruecker
