### ISSUE TITLE
Internet Archive link

### ISSUE THREAD

**Issue by webysther** [sissbruecker/linkding#344]
Hi, great feature send internet archive save page call. I want to know if is possible to create a link to internet archive when the bookmark is create, example:

When point to `20220915000000` **YYYYMMDD**000000 the archive will open the first snapshot:

https://web.archive.org/web/20220915000000/https://github.com/sissbruecker/linkding

This is really good when in the future we need to access the version that is read/saved.

**Comment by sissbruecker** [comment]
Since the latest release (1.15.0) the feature works like this:
- when you save a bookmark, linkding tries to create a new snapshot through the wayback API, so that snapshot would become the latest one the the archive has available, recording the website as it was at the time you bookmarked it
- if creating a new snapshot fails for some reason, then linkding searches the latest snapshot that it can find for that website and stores that - that would result in the same outcome that you described: use the nearest snapshot for the timestamp when you bookmarked it

So the existing logic should cover what you want, and actually more, as it also tries to record a new snapshot for a website when you bookmark it.

**Comment by sissbruecker** [comment]
Looks like this is resolved.
