### ISSUE TITLE
feature request: tag edit

### ISSUE THREAD

**Issue by BeyondIM** [sissbruecker/linkding#35]
Thank you for your great work. I found linkding was missing tag edit function. Could you can it. tks.

**Comment by sissbruecker** [comment]
@BeyondIM Since linkding is built with Django, it also features an admin panel where you can manage all entities. You can access the admin through:

https://linkding.my-domain.com/admin/

Or specifically the tags through:

https://linkding.my-domain.com/admin/bookmarks/tag/

I thought about implementing a tag management UI, but it felt like I would just duplicate the existing work.

**Comment by BeyondIM** [comment]
Thank you very much.
