### ISSUE TITLE
Possibility of synchronization. Bookmark server example (mozilla sync)

### ISSUE THREAD

**Issue by v0r0n0v** [sissbruecker/linkding#361]
Hello, I will be grateful to you if you make it possible to synchronize with the bookmark server. An example of work (Mozilla sync). In Mozilla, for example, there is a parameter

in about:config, the value of the services.sync.tokenServerURI key
 
I'll be happy to see bookmarks in my bookmarks bar that will sync with my server.
Now, as far as I understand, it is available only by going to the url.

If possible, provide an answer if there is such a possibility.

Thank you.

**Comment by heyheyhello** [comment]
Fwiw this could be implemented by a browser extension as a kind of "bridge" between Mozilla Sync and Linkding. _Tab Stash_ is a Firefox extension that reads and writes bookmarks for all of its state - which is nice because the bookmarks will naturally sync over Mozilla's servers without needing to update all of your devices' about:configs. There are Linkding browser extensions which read data from Linkding's REST API, and it would make sense for them to also update bookmarks.

**Comment by sissbruecker** [comment]
Hey, not really interested in this. It should be possible to implement your own tool that syncs bookmarks between linkding and other servers.
