### ISSUE TITLE
feature request: synchronize user database with an external user directory

### ISSUE THREAD

**Issue by Lucas-C** [sissbruecker/linkding#376]
Hi!

Thank you for developping this project as open-source! ❤️

In my experience, in order for this kind of useful tool to be used in the context of a medium/big company,
it would be very handy / necesseray for it to sync with an existing user database,
for example through protocols like ActiveDirectory or LDAP.

Would you be open to have such feature?

**Comment by sissbruecker** [comment]
Hey, not interested in maintaining this. If you want to sync accounts + credentials, you should be able to write a script for this.

Apart from that linkding has [support for authentication proxies](https://github.com/sissbruecker/linkding/blob/master/docs/Options.md#ld_enable_auth_proxy), so that could be an option. Contrary to the documentation, the application will actually create accounts for new users when a request arrives, so creating a large number of accounts should not be a problem as it happens automatically.

**Comment by Lucas-C** [comment]
Thank you for your answer
