### ISSUE TITLE
After reinstalling password rejected

### ISSUE THREAD

**Issue by mrtargaryen** [sissbruecker/linkding#421]
Raspberry Pi 4 B
Raspbian lite
Docker 23

I had to reinstall Linkding on my Raspberry Pi

When I go to the web ui it asks for a username and password , it rejected my previous password 

How do I change the username and password ?

**Comment by mrtargaryen** [comment]
Is there a forum or link describing how to mount a database to linkding? Sorry, I'm only new to linux

**Comment by sissbruecker** [comment]
You should use the second command from this section: https://github.com/sissbruecker/linkding#using-docker. That way the database created by linkding will be stored on the host system, rather than in the Docker container, which means you can delete and recreate the Docker container as often as you like without losing data.

**Comment by mrtargaryen** [comment]
Whats an example of a host data folder to use?

**Comment by mrtargaryen** [comment]
> Don't use the curly brackets, they were intended to indicate that this is a placeholder. When using a Raspberry Pi, the default user should be `pi`. If you wanted to store the linkding database in that users home directory you could use:
> 
> ```
> docker run --name linkding -p 9090:9090 -v /home/pi/linkding:/etc/linkding/data -d sissbruecker/linkding:latest
> ```
> 
> You'll have to create the linkding directory in the user's home directory first.

I actually figured out the brackets weren't necessary, thanks for taking the time out to help me.
