### ISSUE TITLE
Android Shortcut App: "invalid URL"

### ISSUE THREAD

**Issue by xteaun** [sissbruecker/linkding#443]
Hi there! 

I have worked through the guides that explain how to set up the Shortcut-App on Android. Unfortunately I am not getting it to work. The error I get when I try to run the bookmark-shortcut is: "invalid URL (linkding.xxxx.xx/api/bookmarks)."

What am I doing wrong? :)

Thanks for your help. 
Christian

**Comment by kzshantonu** [comment]
Did you set the instance URL including the `http://` or `https://` part? Also the URL should end cleanly without any `/`

**Comment by xteaun** [comment]
I tried both, http and https. Same error.

**Comment by kzshantonu** [comment]
Are you using a self signed certificate?

**Comment by sissbruecker** [comment]
Closing as stale

**Comment by Kariton** [comment]
hey @sissbruecker 

i have basically the same issue, would you reopen this or prefer a new issue?
but my error is with proto and following slash: `"invalid URL (https://linkding.xxxx.xx/api/bookmarks/)."`

<img width="1440" height="1752" alt="Image" src="https://github.com/user-attachments/assets/a556f97f-d911-405c-8265-15198121eaa5" />

no, i dont use a selfsigned certificate - its an LE one.
browser plugin on PC works.

browsing to that page yields django rest error page for 401 - obviously; because im not authenticated.

**Comment by sissbruecker** [comment]
Can't really help you there, I don't use HTTP Shortcuts or Android. 

What is visible from the URL looks correct, and "Invalid URL" sounds more like HTTP shortcuts not liking your URL, rather than the request failing. Looking at the source code that seems to confirm that: https://github.com/Waboodoo/HTTP-Shortcuts/blob/15ad563f8322f185c35e069e71c446353cedb3a8/HTTPShortcuts/app/src/main/res/values/strings.xml#L902-L903

**Comment by kzshantonu** [comment]
@Kariton install it as a PWA then share any link from any app
