### ISSUE TITLE
Improvements to favicons

### ISSUE THREAD

**Issue by Zottelchen** [sissbruecker/linkding#465]
I really like the favicon function, but here are some possible improvements I noticed:

1. Let the service be selected in the settings.
2. Offer an alternative to the _{url}_ replacer (➡e.g. `https://www.github.com`) - _{domain}_ (➡ `www.github.com`) would help to make it easily work with other services 
3. Don't assume the returned Icon is a png. It could be an .ico
4. Extend the documentation with alternative icon providers:
     * `https://icons.duckduckgo.com/ip3/{domain}.ico` - a privacy respecting alternative
     * `https://besticon-demo.herokuapp.com/icon?url={url}&size=32..64..128&formats=png` - flexible & selfhostable
     * `https://icon.horse/icon/{domain}`
     * `https://favicongrabber.com/api/grab/{domain}` - requires additional work
 5. If using Google by default, this seems to give me better results: `https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url={url}&size=64`

**Comment by sissbruecker** [comment]
Thanks, this seems useful. Offering some more choices for icon providers would be great. Making them selectable in the options is more of a nice to have for me.

Some clarification:
2. Could you elaborate a little bit? I'm not quite sure what you are suggesting, and I'm also not in the context anymore on how the current url placeholder works.
3. Probably doable by inspecting the response headers. Thankfully the extension is also stored in the database field, so it should be doable without breaking changes.
5. Better results how? Like what is better about it?

**Comment by Zottelchen** [comment]
Sure :)
2. Basically right now the replacer is `{url}` - it includes the protocol (typically `https://`). Some icon providers just want the basedomain though without the protocol.
5. For some pages the default [does not provide an icon](https://t1.gstatic.com/faviconV2?url=https://www.vice.com&client=SOCIAL&type=FAVICON), e.g. `https://vice.com`. [My alternative](https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.vice.com&size=64) however does. Additionally, [some images](https://t1.gstatic.com/faviconV2?url=https://www.waveride.at&client=SOCIAL&type=FAVICON) provide an [additional background color](https://t1.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://www.waveride.at&size=64), which makes them easier to see on all theme colors.

**Comment by Zocker1999NET** [comment]
to add to 5.: due to smartphones, in general scaled UIs and other UI elements allowing for bigger icons (e.g. Firefox default homepage with the most relevant pages), most webpages are going away from only providing 16x16 or 32x32 icons and also begin to use other formats as most browsers today support JPEG, PNG, ….

However, Googles default seems to limit itself to provide only 16x16 icons, probably because depending software may only support or expect such icons there. However, the alternative Zottelchen suggested, sets it so Google knows it can return up to 64x64 icons (and, I assume, can be increased if required).

Currently, the bigger icons would make a difference starting at 2x scaled UIs, but maybe you (or someone else) implements a different UI taking advantage of the bigger icons.

**Comment by sissbruecker** [comment]
Thanks for the additional feedback. Regarding the Google provider, it looks like the one suggested by @Zottelchen is pretty much the same (https://t1.gstatic.com/faviconV2), just with additional parameters? So that could just be changed in the default settings to increase the image size for example.

To handle services that just want the domain without the protocol, I guess a separate placeholder such as `{url-without-protocol}` or `{url-domain}` could be added.

**Comment by AprilNEA** [comment]
> To handle services that just want the domain without the protocol, I guess a separate placeholder such as `{url-without-protocol}` or `{url-domain}` could be added.

Yes, we need it. 
This provider is an example https:/faviconkit.com which only accept url without protocol.

If you can tell me where the relevant code is located, I might be able to help with a PR!
