### ISSUE TITLE
latest docker image not pulling the latest version of linkding

### ISSUE THREAD

**Issue by RogueGhost93** [sissbruecker/linkding#468]
Im trying to get to v 1.18 and im using sissbruecker/linkding:latest as the image tag. After pulling is finished linkding is still on Version 	1.17.2 (latest: 1.18.0) and im not sure why or how to fix it. Also when i go to image link provided in documentation "To install linkding using Docker you can just run the latest [image](https://hub.docker.com/repository/docker/sissbruecker/linkding) from Docker Hub:" it requiress login, maybe that could be the reason due to recent docker hub changes?. Im desparate to search tags without # so any help is appreciated :D

**Comment by sissbruecker** [comment]
Pulling just downloads the image, you also need to create a new container using that image. Also make sure that you have used a volume binding for creating your initial container, and that your linkding database is stored on the host system. Otherwise deleting the container will delete all data as well.

You can take a look at the install script as an example:
https://github.com/sissbruecker/linkding/blob/67ee896a46a3900e907787fb237a3cb4a8ef3790/install-linkding.sh#L31-L42

**Comment by gingerbeardman** [comment]
I'm using [watchtower](https://github.com/containrrr/watchtower) to update some of my docker containers to latest when new versions become available.

**Comment by RogueGhost93** [comment]
> I'm using [watchtower](https://github.com/containrrr/watchtower) to update some of my docker containers to latest when new versions become available.
Yea me too its just setup to run once a week but this update i was eagerly waiting for :D
It works now though, i believe i forgot to recreate the container or something....my bad
