### ISSUE TITLE
Unexpected operation with exotic characters

### ISSUE THREAD

**Issue by gingerbeardman** [sissbruecker/linkding#481]
1. consider this URL: https://en.wiktionary.org/wiki/人
2. and its encoded form: https://en.wiktionary.org/wiki/%E4%BA%BA

if the encoded form https://en.wiktionary.org/wiki/%E4%BA%BA is in the database (which is how my apps saves it):
```
GET /api/bookmarks/?q=https://en.wiktionary.org/wiki/%E4%BA%BA
```
- zero results

if I edit the Linkding database to force the URL to be represented by its UTF8 form (which is how linkding web interface saves it)
so https://en.wiktionary.org/wiki/人 is in the database
and then do the same search query for the encoded form

```
GET /api/bookmarks/?q=https://en.wiktionary.org/wiki/%E4%BA%BA
```
- 1 result!

I'm not sure I understand what is going on here.

Thoughts appreciated.

**bonus bug**
- linkding web interface grabs the page title as `дәә - Wiktionary` instead of `人 - Wiktionary`

**Comment by sissbruecker** [comment]
When making a request, query params need to be encoded. Likewise, when processing a request, query params need to be decoded. So the linkding REST API decodes the `q` param to `https://en.wiktionary.org/wiki/人`, which is what is searched for in the database. 

What you need to do is encode the `q` param in your client, so that when it gets decoded on the server it gets `https://en.wiktionary.org/wiki/%E4%BA%BA` as a result. With the encoded param the GET request should look like this:
```
GET /api/bookmarks/?q=https%3A%2F%2Fen.wiktionary.org%2Fwiki%2F%25E4%25BA%25BA
```
You can double check this in the linkding UI: add a bookmark with the URL, and then search for the same URL, check your browser's address bar how the query param is encoded.

---

The title not being parsed correctly is indeed a bug, fixed with https://github.com/sissbruecker/linkding/pull/482.

**Comment by gingerbeardman** [comment]
Thanks for fixing the bug!

> With the encoded param the GET request should look like this:

Thanks, appreciated.

The text I was quoting was copied from the Django REST framework debug page that appears if you issue issue an API request GET url by simply typing it into the browser address bar.

That complicates things, because the URL is decoded for display in the browser address bar, and so on, it's easy to lose sight of what is what.

![image](https://github.com/sissbruecker/linkding/assets/49612/a7a2494a-fa37-45fd-9274-e74affed7128)

![image](https://github.com/sissbruecker/linkding/assets/49612/38e699aa-81e5-4d44-96b9-9536755c5f05)

**Comment by gingerbeardman** [comment]
For general interest, it turned out my issue was related my API "middleware", which is written in PHP (because I'm middle-aged) and whose `urlencode()` function seems outdated.

It couldn't handle the following URL: https://jisho.org/search/人%20%23kanji

So it took a bit of hacking to work around.
