### ISSUE TITLE
Expanded support for shared flag

### ISSUE THREAD

**Issue by gingerbeardman** [sissbruecker/linkding#484]
If this is in the roadmap and I have missed it, apologies.

Soon after issue #204 was closed initial support for shared tag was added to Linkding.

Shared can be set and queried using the API, but full support is not yet reached.

Observations:
- no front end way to set shared flag when adding a bookmark (in the same way as "Mark as unread" works)
- shared status is not displayed in the list view
- import strips private flag rather than mapping it to shared
- exporting sets private=0/false even if bookmark has shared flag set as shared=true

**Comment by gingerbeardman** [comment]
I have a bit of time coming up, I could get started on any import/export changes? any thoughts?

**Comment by gingerbeardman** [comment]
Another weekend approaches, shall I begin work on this?

**Comment by sissbruecker** [comment]
Some feedback on this:
- You need to enable bookmark sharing in the settings in order for a checkbox in the bookmark form to show up
- Shared status is indeed not shown in the list. I'm being careful with adding more stuff to bookmark items, in order to keep the list readable. An opinionated choice, but you're the first to want this, so maybe not very relevant.

Regarding mapping shared bookmarks to the private flag, I'm not convinced that this is the right approach, as these have different meanings:
- At least in Pinboard, a non-private bookmark is a public one, which means everyone, even anonymous users can see it.
- In Linkding, a shared bookmark is only shared with other authenticated users.

That results in two issues:
- Users, especially existing ones, might not expect that importing a non-private bookmark now suddenly shares it with everyone else in their installation
- If support for public bookmarks ever gets added, then the private flag is already mapped to something else

**Comment by gingerbeardman** [comment]
Thanks for your thoughts.

>  but you're the first to want this

I think it would be easy to argue that the users in issue #204 also want it?

> Users, especially existing ones, might not expect that importing a non-private bookmark now suddenly shares it with everyone else in their installation

I can't speak for the number of installs that have multiple users, but this scenario would be easy to cope with by defaulting the setting to off (no change to behaviour, just like the one to enable bookmark sharing). 

> If support for public bookmarks ever gets added, then the private flag is already mapped to something else

My first thought is that the a private bool (0/1) could be transformed into an enum (0/1/2) for an easy migration to private/localshare/publicshare. Just an idea.

**Comment by sissbruecker** [comment]
I added a setting that allows public access to shared bookmarks: https://github.com/sissbruecker/linkding/pull/503. With that, shared now pretty much maps to public, or not private. As such, implementing that mapping in the import / export makes more sense. Still, I'd consider adding that as an option, maybe as checkboxes next to the import / export buttons.

**Comment by gingerbeardman** [comment]
Many thanks!

Is the mapping something you plan to do? or are you looking for a PR?

**Comment by gingerbeardman** [comment]
I was thinking, if entries that were marked with a CSS class for "shared" (and not) then I could style these myself using my own browser stylesheet. Even if the class is unused by Linkding styles, it would be enough.

**Comment by sissbruecker** [comment]
Added mapping of the `PRIVATE` flag in https://github.com/sissbruecker/linkding/pull/505.

Sure, adding a CSS class to bookmarks would be fine, you could open a PR for that. Another thing that could be useful is a search keyword for shared bookmarks, similar to `!untagged` or `!unread`. That would give a clear list of shared bookmarks at least.
