### ISSUE TITLE
Background tasks not running

### ISSUE THREAD

**Issue by blipdrifter** [sissbruecker/linkding#490]
I've been using linkding on my VPS for the past year or so, and I've liked it so far. However, after I upgraded it one day (don't remember exactly when), suddenly my install refuses to send websites to the Internet Archive or add favicons for every website at all, despite having both of those features enabled in the settings (as well as pressing Refresh Favicons to no avail). I finally decided to go into the admin panel to see if it logged anything, when I found out that none of the background tasks that have processed in the past 6 months have had 0 attempts. Is this normal?

![image](https://github.com/sissbruecker/linkding/assets/11656143/081e5693-bf71-4103-9c50-1137fa12da56)

There's also nothing in the Completed Tasks section, by the way. (Also running on Docker on Ubuntu 18.04.) Please help!

**Comment by sissbruecker** [comment]
I can only think of two possibilities:
- Tasks are locked by the task processor when it starts working on them. If the processor was shut down unexpectedly the locks might not have been released, and even after starting the processor again it doesn't do anything because there are still locked tasks. You can verify that by checking in the admin whether one task has something under `Locked By`. 
- The task processor is not running at all. In that case none of the tasks has something under `Locked By`

In both cases the only thing I can recommend is to recreate the Docker container and see if that helps.

**Comment by sissbruecker** [comment]
Since this is quite stale, I'll close the issue for now. If you still want to look into this, then please open a new issue and provide a DB file that allows me to reproduce the issue.
