### ISSUE TITLE
[Feature request] polishing the Bookmark list UI

### ISSUE THREAD

**Issue by giddisey** [sissbruecker/linkding#528]
I am enjoying Linkding so far but found the UI quite dated compared to some, more modern looking, speed dials and bookmark managers. For example - 

<img width="512" alt="heimdallscreenshot" src="https://github.com/sissbruecker/linkding/assets/15666566/7207c8c6-9cdc-4c0f-9948-e679606e164c">

I decided to have a play with a CSS override extension and came up with the following which I think is a huge improvement -

![image](https://github.com/sissbruecker/linkding/assets/15666566/a695334d-6a26-4274-b416-961e08500b80)

Key changes - 

- Move to a 2 column layout
- Increase max width of the page
- Add a border around each bookmark
- Increase padding between bookmarks

This is the css I use - 

`
.container {
  max-width: 1400px;
}

ul.bookmark-list {
  columns: 2;
  -webkit-columns: 2;
  -moz-columns: 2;
}

ul.bookmark-list li {
  border-radius: 20px;
  border: 2px solid #73AD21;
  padding: 15px;
  width: 100%;
  height: 100px; 
  margin-top: 0;
  margin-bottom: 20px;
  break-inside: avoid-column;
}
`

**Comment by Ratfiend** [comment]
I linke the two column design 👍 

In this context it would be a nice feature to provide a possibility to add a custom css file to linkding. So (color-) themes and specific styles like the two-colum desing from giddisey can be applied more easily and update-safe.

Something like custom-light.css, custom-dark.css and custom-misc.css (which is loaded at last).
Also this location can have its own docker volume to persist any customizations.

**Comment by joel72265** [comment]
I agree with Rafiend on,

- .css to change to 2 or more columns
- .css to change the theme
- .css to change layout to Card view (images with bookmarks)
- Export bookmarks as YYYY-MM-DD bookmarks.html

**Comment by 986244073** [comment]
I agree with Rafiend on,

**Comment by sissbruecker** [comment]
No plans for that. In general the bookmark list should be optimized for readability / quickly finding bookmarks, which is usually better as a straight list, as you only have to scan from top to bottom rather than left-right, top-bottom. A two column layout also has the issue that bookmarks will constantly switch from one column to the other as you keep adding new bookmarks.

A multi-column layout makes more sense for a dashboard where you only irregularly add new links, and ideally can customize the location of a link so that you can build up muscle memory where you can find that specific link. A dashboard might be an option for the future, but that is a separate topic.
