### ISSUE TITLE
Add PWA support to use "Share with..." on Android

### ISSUE THREAD

**Issue by edersong** [sissbruecker/linkding#558]
Add PWA support to use "Share with..." on Android to save bookmarks to a "Read it later" tag

**Comment by sokai** [comment]
FYI @edersong: https://github.com/linka-app/linka seems interesting

**Comment by dahamsta** [comment]
Just want to bump this, for PWA support in general.

**Comment by sissbruecker** [comment]
Dupe of #98

**Comment by danielyrovas** [comment]
Hey @edersong, are you interested in testing an Android app? I have written a small unofficial client for LinkDing [here](https://github.com/danielyrovas/linklater). It can add tags to bookmarks when you save them.
You can install it directly from the releases or using [Obtainium](https://github.com/ImranR98/Obtainium).

**Comment by karlhorky** [comment]
The web-share-target PWA API has been implemented in v1.25.0 (Mar 2024), so IIUC "Share with..." should work with a PWA on Android now:

- https://github.com/sissbruecker/linkding/pull/630
- https://github.com/sissbruecker/linkding/releases/tag/v1.25.0

Otherwise, there appears to be a Flutter app called Linkdy from @JGeek00 which is available in the Play Store:

- https://github.com/JGeek00/linkdy
