### ISSUE TITLE
Exported file does not include bookmarks from archive

### ISSUE THREAD

**Issue by xuhcc** [sissbruecker/linkding#564]
Settings - General - Export (Export all bookmarks in Netscape HTML format)

The resulting file only contains "Active" bookmarks, but I think it should contain archived ones as well.

Linkding version: 1.22.0

**Comment by sissbruecker** [comment]
Thanks for highlighting this, it probably should include archived bookmarks as well. One thing to consider is that archived bookmarks would ideally be marked as such, so that on import they become archived bookmarks again. I guess that would require extending the Netscape HTML format somewhat, for example adding an attribute like `ARCHIVED="1"`. I'm always a bit hesitant with that given that the format is so brittle, and custom parser implementations might be too.

**Comment by zoredache** [comment]
You could translate it to a tag.  Maybe something like `linkding:archived`.  Might also give the option to export with, and without the archived links.

**Comment by xuhcc** [comment]
Archived bookmarks are now included. Thank you!
