### ISSUE TITLE
Adding the option to add multiple URLs?

### ISSUE THREAD

**Issue by gitcrook** [sissbruecker/linkding#566]
Is there already a way to add multiple URLs to a single bookmark? This would be helpful for mirror sites, saving a URL that relates to the bookmark (like status monitoring sites) or maybe even having the tor link version of the website on the same bookmarks. I would guess it defaults to the 1st URL in the order, maybe with some kind dropdown button on the side to show the URL options.

**Comment by sissbruecker** [comment]
You can put any number of links into the bookmark notes by formatting them with Markdown:

![Bildschirmfoto 2023-11-04 um 10 00 33](https://github.com/sissbruecker/linkding/assets/357820/ba54be1a-aef3-428c-987b-9481eb43ae4d)

**Comment by aerz** [comment]
> You can put any number of links into the bookmark notes by formatting them with Markdown:

When browsing open-source projects on GitHub, I sometimes rediscover projects I've previously bookmarked using the browser addon (e.g., https://github.com/coollabsio/coolify). When visiting their website (e.g., https://coolify.io/), I end up saving it again because the addon doesn't notify me that I've already bookmarked it. Could you reconsider to add this feature? @sissbruecker 

![Image](https://github.com/user-attachments/assets/074fc001-1310-4d8b-9e8e-4b3d955220a1)
