### ISSUE TITLE
Improvement: Dropping sass-processor dependency

### ISSUE THREAD

**Issue by jonathan-s** [sissbruecker/linkding#592]
As evidenced here > https://twitter.com/dhh/status/1735435171342737866 MDN writes more about it > https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting

Modern CSS manages to nest CSS; so there shouldn't really be a need for a sass processor. You could use plain CSS.

**Comment by krzysztofjeziorny** [comment]
[CSS nesting](https://caniuse.com/css-nesting) has still some issues, but for sure it will make the life easier.

**Comment by sissbruecker** [comment]
linkding mostly uses SASS because the CSS library that linkding uses (Spectre.css) is based on that, so it was a necessity to customize the SASS variables exposed by the library. It's also using some SASS helper functions, for example to modify colors.

Over time I have added a lot of customizations, and Spectre.css doesn't really get any improvements anymore, so it could be an option to "eject" the Spectre related CSS, in the same step replace SASS with CSS variables, and hard-code / extract the stuff calculated by functions. Still quite a bit of effort. It would help speed up the Docker build, which seems to be 50% building lib-sass, but I don't see myself spending time on this soon.
