### ISSUE TITLE
[Feature request] More/custom themes

### ISSUE THREAD

**Issue by thany** [sissbruecker/linkding#595]
I would personally appreciate a few more options in terms of themes. Dark and light are good to have, and we should keep that 👍🏻

But a few more options for those who might not fully appreciate the purple/green setting in dark mode? And then maybe also throw in a high-contrast theme for the folks who need that?

Or go all the way, and add a number of fields where users can pick and choose colours, similar to what DuckDuckGo does.

**Comment by rghedin** [comment]
On this regard, just custom accent colors would be nice. (I like Linkding's purple, but I'd rather use another color 👀😄)

**Comment by thany** [comment]
I don't see accent colours as being a theme, personally. But it's better than one single hard-coded colour, for sure.

One disadvantage: it'll be more difficult to add full-fletched theming support in the future, without dropping support for an accent colour. It seems every theme would then have to somehow support that accent colour setting.

**Comment by rghedin** [comment]
Yeah, they are different. I'm not involved in Linkding development, so it's just an opinion of a random guy: theming adds lots of complexity to the project. Maybe feasible, but the benefit seems too little for the effort needed. Since most Linkding instances are single user (I guess?), and theming is something really subjective, maybe customizing Linkding via user style/userscript would be a better path?

**Comment by thany** [comment]
No worries, I was only stating my concerns. I think we can agree there are definitely pros and cons for either approach.

I'm curious to what the author thinks is best.

**Comment by sissbruecker** [comment]
Personally I don't want to maintain multiple themes, figuring out how to style some new feature between light and dark theme is already challenging enough. I also can't make any guarantees regarding CSS classes or DOM structure for applying a custom theme, if I need to fix something and an easy solution requires changing the DOM, I'll do it. Still, the DOM and CSS classes should be mostly stable, so I would suggest to go with the userscript route for now. I would maybe consider adding a text area for custom CSS to the settings to make custom theming easier, or adding a CSS class to some element that is not targetable otherwise. Another improvement could be to use CSS variables instead of the current SCSS variables, which would make it easier to apply custom colors to multiple things at once.
