### ISSUE TITLE
[Question] How to install manually?

### ISSUE THREAD

**Issue by rmszc81** [sissbruecker/linkding#629]
Hello gentlemen,

first, thank you very much for the great tool. Linkding is awesome.

second, how to install manually? I'm migrating my linux servers to freebsd and I'd like to bring linkding together.

best
ross.

**Comment by jonathan-s** [comment]
It seems like there is a bit of context missing. Have you tried running the app from the docker container?

**Comment by rmszc81** [comment]
@jonathan-s 

Docker container in freebsd....? well, first docker and freebsd, don't fit together.  By running docker in freebsd (what's not recommended, by design), it will install a tiny linux VM just to run the containers.

It's better to install a tiny linux vm such as alpine linux using bhyve rather than using docker. For freebsd, there's jails. I guess you missed the point of my question?

Knowing how to install manually, I can even create a port for FreeBSD and run natively, instead of using VMs or containers.

Thanks!
Best,
Ross

**Comment by jonathan-s** [comment]
Perhaps I'm not very helpful in this answer, but the clue for getting this to run manually is in the [dockerfile](https://github.com/sissbruecker/linkding/blob/master/docker/alpine.Dockerfile) and then in the [bootstrap](https://github.com/sissbruecker/linkding/blob/master/bootstrap.sh) file. 

There isn't a manual for manually installing it otherwise. Though, those two files should give you enough of a hint to get things running imho.

**Comment by sissbruecker** [comment]
To reduce maintenance and support questions, I don't want to support manual installations, the Docker image was for me the best option to provide the app as a "single thing" that people need to get running. But yeah, that doesn't help if the environment doesn't support Docker.

As mentioned above, your best bet is to dig through what Docker does and replicate that manually.

**Comment by Drallas** [comment]
Regarding this closed discussion, it would be wonderful to have a @tteck Helper-Scripts to create an LXC container on Proxmox, for this incredible application!
