### ISSUE TITLE
Option to create bookmarks public

### ISSUE THREAD

**Issue by Ullarah** [sissbruecker/linkding#70]
Would it be possible to implement an option to have the bookmark display in a public list?

Say if you were to do to /public at the end of the url it would display a list of URLs that users have set as public when creating the bookmark.  Probably not high on the todo list, but would be nice to see if possible 👍 

Great bookmark software.  Been using it for over a week now!

**Comment by sissbruecker** [comment]
@Ullarah I get the idea in that you want to share specific bookmarks with friends, colleagues or a community. However I feel that this is out of scope for this project. 

Still this is very much possible by writing a third party application that utilizes the REST API. I know of another user who has done something similar: tagging all bookmarks that should be published on their website with a specific tag and then writing a script that fetches all bookmarks for that tag. Then render the data in some way (e.g. HTML file) so that it can be hosted on a webpage. They documented the process here: https://box.matto.nl/perl-script-to-fetch-bookmarks-from-linkding-rest-api.html

**Comment by Ullarah** [comment]
That is a-ok!  Thank you for sending through that link, it’ll be perfect for what I am trying to achieve!

**Comment by Metal-Frog** [comment]
Out of the box public bookmarks would be great!
