### ISSUE TITLE
How can I use it offline?

### ISSUE THREAD

**Issue by okuc** [sissbruecker/linkding#711]
Thanks for developing such a great app, I really like it. But I'm having a problem now, I deployed it to a server on my intranet, but when I'm not working on my intranet, I can't access my bookmarks that I've bookmarked.
I would like to ask if there is a corresponding solution in this case, e.g.: provide local cache, provide offline client?

**Comment by sissbruecker** [comment]
linkding itself doesn't support offline use, and it's unlikely that it ever will as most of the UI logic is on the server-side.

You might want to look into exposing your server so that you can access it remotely. If you don't just want to open it up to the internet, you could look into something like [TailScale](https://tailscale.com/) that allows creating a custom network where only your own devices can access a server from your intranet.
