### ISSUE TITLE
Would you like to get some of the features from my fork?

### ISSUE THREAD

**Issue by vslinko** [sissbruecker/linkding#729]
I made some features for myself:

- [auto tagging](https://github.com/vslinko/linkding/commit/4c4bcb3fc38b71b249f7467c5687e437adccc11e)
- [previews lazy loading](https://github.com/vslinko/linkding/commit/49c77f14d740c887242e12130c18c66cdec40796)
- [disable tag grouping](https://github.com/vslinko/linkding/commit/892884a6cdc3c1e48df8efe5c230075902f15f71)
- [Hide tooltip on mobile](https://github.com/vslinko/linkding/commit/1d84127d4826cba7a38f87553bc3621e9093fe09)
- [pinned bookmarks](https://github.com/vslinko/linkding/commit/e129a320b80b1d56b1c07b6582ef51a85c7ca0d8)

Maybe something might be interesting to merge into the original repo? I could make a fully functional PR with good UI, tests, etc.

**Comment by sissbruecker** [comment]
Thanks, those look useful. Some thoughts:
- Auto tagging: Definitely a cool idea, though that could require a bit of effort to get right. For one there would need to be a proper UI for configuring the auto tags. Another thing is that you might want to see which tags will automatically get assigned when adding a bookmark through the form, and possibly through the extension. Not a blocker though.
- Preview lazy loading: Makes sense, regarding implementation it should be possible to use the loading attribute on the image though: https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes
- Disable tag grouping: It seems straightforward to implement and I can see that the alphabetical grouping doesn't work for everyone. I guess adding this as an option would be fine, though I'd structure it so that the setting would be a select where you can choose how to group tags. By default it's alphabetical, with a second option to just disable grouping. Then later on maybe more grouping types can be added.
- Hide tooltip on mobile: Missing context here, what's the issue? If there's a UX problem, I'm fine with it getting fixed, though a bug issue with some context would help.
- Pinned bookmarks: Maybe, I think that would require some more thought. Making pinned bookmarks always show up at the top would be super annoying for me, I'd prefer a filter or maybe even a separate view for viewing them. Another issue is the order in which pinned bookmarks are displayed. I think if there are pins, then it should be possible to define a custom order for those, so that adding a new pin does not interfere with the order that I have memorized. And if you have a lot of pins, then you might want to cluster them into categories. At that point you basically get close to a custom dashboard, which IMO is the most useful variant of this concept, but also the most complex one to implement. There's an [existing issue](https://github.com/sissbruecker/linkding/issues/578) for that so maybe continue the discussion there for now.

**Comment by vslinko** [comment]
> Preview lazy loading: Makes sense, regarding implementation it should be possible to use the loading attribute on the image though: https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes

I prefer JS implementation because Safari loads all the lazy images in the background. The lazy attribute just lowers the priority. 

> If there's a UX problem, I'm fine with it getting fixed, though a bug issue with some context would help

If you click on a link on mobile (I tried on iOS), then go back, the link will be in focus and the tooltip will overlap half of the link, which is annoying because it's hard to take the focus off on mobile.

**Comment by vslinko** [comment]
Thanks for the feedback, I'll think about how to make good PRs.
