### ISSUE TITLE
Allow snapshotting of sites like reddit

### ISSUE THREAD

**Issue by nadir-ishiguro** [sissbruecker/linkding#732]
Love the snapshot feature, but about half the bookmarks I create are of reddit posts. As reddit implemented restrictions on users that are not logged in, every snapshot looks like this:

![reddit_blocked](https://github.com/sissbruecker/linkding/assets/23151917/05f4dba9-fc1a-409d-9aa5-67f696e3924e)

Normally I see projects that make use of something like playwright enable users to manually upload a cookie of some sort, but that seems like a bad fit for linkding.

I've seen issue https://github.com/sissbruecker/linkding/issues/712 where you said getting the html from the extension might be an option.

I've mainly opened this issue to maybe add it as another potential use case for that type of enhancement.

It's not ideal as it doesn't cover all existing bookmarks, but it would be a great feature nonetheless.

**Comment by sissbruecker** [comment]
Reddit apparently needs a [custom user agent](https://github.com/sissbruecker/linkding/blob/master/docs/Options.md#ld_singlefile_options), see the related issue: https://github.com/sissbruecker/linkding/issues/690. I just did a brief test and it still seems to work fine.

Otherwise I'd prefer to keep the discussion in #712, as currently it's not clear what the individual issues and possible solutions are.

**Comment by nadir-ishiguro** [comment]
Thank you very much, that solved my issue. 

Sorry for not figuring that out myself and bothering you.
