### ISSUE TITLE
[feature request] Popular links

### ISSUE THREAD

**Issue by claudiorrrr** [sissbruecker/linkding#746]
Since forever I have https://pinboard.in/popular/ page on my bookmarks. It's a great page for looking at popular links saved by users at Pinboard. 

I truly love linkding, and I would love it more if this feature –meaning, a page for popular links, probably with opt-in, etc, etc- is implemented.

**Comment by sissbruecker** [comment]
pinboard.in is a central instance with thousands of users, while linkding is a self-hosted app that doesn't know anything about the data in the instances that other people host. On pinboard that feature is useful because hundreds of people could have bookmarked the same link, making it popular. In linkding, at best you could show links that multiple users on the same instance have bookmarked, which doesn't seem very useful / meaningful since there's probably going to be very little overlap due to the much lower number of users. The next best thing in linkding is sharing bookmarks, so if you have other users on your instance (family, friends, colleagues) and they share stuff, you could take a look at what they have shared from time to time.
