### ISSUE TITLE
[Feature request] Remove Dulicates

### ISSUE THREAD

**Issue by ben7sys** [sissbruecker/linkding#766]
As my title mentions, it would be great to be able to remove dulplicate bookmarks.

**Comment by sissbruecker** [comment]
How did you get duplicates in the first place?

**Comment by edgardmello** [comment]
when I imported old bookmarks. It would be really nice to be able to remove duplicate entries. btw the app is awesome and very fast.

**Comment by sissbruecker** [comment]
Let's close this in favor of https://github.com/sissbruecker/linkding/issues/751 then.

**Comment by siebenmeister** [comment]
> How did you get duplicates in the first place?

When i started to use this awesome linkding gem, i imported a lot of bookmarks from different platforms and browsers, which resulted in many duplicate bookmarks. In my opinion, it would be useful to introduce a feature that not only removes duplicates during import but also serves as a general cleaning function. This would be especially helpful because i have to keep using different browsers that can't synchronize bookmarks with each other.

**Comment by sissbruecker** [comment]
@siebenmeister Please add your comment to the other issue then so it doesn't get lost.
