### ISSUE TITLE
Missing "description" request body parameter in API causes 500

### ISSUE THREAD

**Issue by bachya** [sissbruecker/linkding#78]
Version: 1.3.1
Architecture: Docker

When I attempt to omit the `description` request body parameter in the `POST /api/bookmarks/` API call, I get a 500 response. The API should either instruct me to include this field or gracefully handle its absence.

**Comment by sissbruecker** [comment]
Looked into it, there's two issues here:
- validation on the endpoint is not correctly defined
- model validation allows blank, but not empty values for title, description

For now the minimal payload for creating bookmarks would be:
```
{
    "url": "https://github.com/sissbruecker/linkding/issues/78",
    "title": "",
    "description": "",
    "tag_names": []
}
```

**Comment by sissbruecker** [comment]
Marked the respective fields as optional in the serializer. The minimal payload is now:
```
{
    "url": "https://github.com/sissbruecker/linkding/issues/78"
}
```

Note that empy text fields (title, description) are represented by an empty string `""` instead of `null`. That is the best practice recommended by Django. As such it is OK to omit the field, pass an empty string or a full string. But it is not allowed to set the JSON property to `null`. Also all empty text fields will be returned as empty string, even if you did not pass a value for it.
