### ISSUE TITLE
Make scraped title and description editable

### ISSUE THREAD

**Issue by tanrak** [sissbruecker/linkding#80]
The grayed scraped entries should be editable at "new bookmark" dialog.

**Comment by Export33** [comment]
I like the idea.
Let the text greyed out while not entering a field to suggest an auto input.
When focussed select the whole scraped text. You could easily

* overwrite the whole text with an single input because the text is selected
* click into the text and change a certain area
* if theres any text inserted by the user before the scraping is done use the inserted text (as it is right now)

**Comment by sissbruecker** [comment]
I also like the idea, however the concept is that the input must be empty if you want to use the scraped values, so prefilling the inputs was not appropriate and would make it more difficult to replace it with a custom value, which is the more important use-case.

I gave it a try to preselect the text when focussing the input, but that was too finicky. When clicking into the input the browser might start a text selection when moving the mouse / cursor at the same time. That in turn leads to a half selected text which is again problematic if you just want to quickly enter a custom value.

As an alternative I implemented buttons that allow you to copy the scraped values into the input. That is a bit more inconvenient for this use-case, but I find it a reasonable trade-off.

**Comment by Export33** [comment]
Using a button is totally ok. It is easyly done and works fine for my few tests.

But i think the line-weight of the button itself does not fit to the overall ui-design because it´s too thick. Replacing it with a thinner icon or just a character would look better.

Example `<`:

![grafik](https://user-images.githubusercontent.com/25232960/113520372-e84c2400-9592-11eb-810f-e96b2c335fde.png)
