### ISSUE TITLE
where have my files gone?

### ISSUE THREAD

**Issue by jcaust** [sissbruecker/linkding#832]
linkding files have disappeared . I had some folder permission issues in Synology file station that's not related to linkding . after modifying these permissions , linkding is gone/not working .
it was working fine before. 
Synology ds1522+ docker via portainer .

![linkding Synology docker-3of3](https://github.com/user-attachments/assets/78628cc3-50e8-4b9b-a269-cf614aa5f633)
![linkding Synology docker-1of3](https://github.com/user-attachments/assets/c85785c9-e881-4efb-8e52-3b88f4696881)
![linkding Synology docker-2of3](https://github.com/user-attachments/assets/56caf332-15ce-4b83-8d92-d1ca869254b7)

**Comment by sissbruecker** [comment]
Sorry to hear that, however linkding does not remove any folders, nor would it have access to your backups / snapshots. 

As such it seems your issue is related to either Synology or Portainer. If the snapshots are created by Synology then it seems like the issue is there. Otherwise it's probably an issue with Portainer. Note that I don't maintain the Portainer configuration myself, you'll have to bring this up with whoever is maintaining that.

**Comment by jcaust** [comment]
thanks . however , it's not related to portainer or snapshots. no maintenance or modification was done to these.
there has also been no file deletions.
the whole internal folder of linkding disappeared .

could this happen if an update is done on linkding ? (I'll need to check when last updated). however , i am sure an update was done before this issue and linkding had been working for weeks .

**Comment by jcaust** [comment]
oh, and all of the bookmarks, this is the one. thanks for developing .
fyi, i have multiple backups now. your suggestion in docs and Synology tool/app to backup .

**Comment by sissbruecker** [comment]
linkding runs in a Docker container and as such is isolated from the rest of your system. It can not manipulate any files that you have not explicitly mounted into the container. If files in your backup location are gone, which the Docker container can not access, then something else must have happened. I'd guess that your files are probably still there, but due to the permission change they don't show up in the Synology web UI anymore.

**Comment by jcaust** [comment]
ok. thanks . appreciate your reply .

James
/|\';;'/|\
BatsRule.com🦇
________________________________

**Comment by jcaust** [comment]
just one more thing I'm curious about..
/volume1/docker/linkdingplus: etc/linkdingplus/data
the "etc/linkdingplus/data" does this hold any data. i assume its just a pointer ?

thanks

James

________________________________
