### ISSUE TITLE
Expose `date_added` in UI

### ISSUE THREAD

**Issue by michaelx** [sissbruecker/linkding#85]
What do you think about exposing the bookmark `date_added` field in the UI? I have many bookmarks and like how Pinboard gives me a chronological reference.

As I am a first poster in this project, I want to thank you for publishing it, it's really fantastic!

**Comment by sissbruecker** [comment]
This is definitely a good idea. I took a swing at it here: #95 . 

Some thoughts:
1. Should this display an absolute date or a relative natural date (e.g. "5 months ago")? In the PR I use a localized absolute date which was easy. For natural dates there is a Django util which works ok, but is too specific for this use case (e.g. "two weeks and two days ago"). I might still change this, but would have to dig out a library that is a good fit.
2. ATM the bookmark list is actually sorted by date_modified instead of date_added. This means that the displayed dates would be out of order. I never thought too deeply about this decision, but in hindsight ordering by date_added seems to make more sense. Currently just adding / removing a tag on an old bookmark pushes it to the top of the list which is probably unexpected. In the PR I switched ordering to use date_added, but not 100% sure yet.

**Comment by Gatada** [comment]
I think I would like to see an updated bookmark resurface.

Why not show both:
_15.08.20 (edited 4 days ago)_

**Comment by sissbruecker** [comment]
IMO a bookmark is not really a document that needs a history. You're not really making considerable changes to the content itself (i.e. the linked website), but only to it's description and organization. As such I think the implied information when something was added (by ordering by date_added) is more useful, since most bookmarks actually loose value over time. 

Showing the edited date would be little effort, but here I would prefer to keep the bookmark items as clean as possible.

**Comment by michaelx** [comment]
**Date formatting**

I like it how Apple is handling it:

- Today (Time): 12:34 PM
- This week (weekday): Monday
- Older (localized absolute): 01.01.21

Of course this is opinionated. So you could make it a setting too, but at least I don't like to use relative dates for very old dates, because I often see myself calculating it back to the absolute date in my head, e.g. when exactly was `5 months ago`. I use `date-fns` for it.

**What to display**

When the bookmark was originally added by the user.

I wouldn't like if bookmarks get pushed to the top when I just edit it. You would then also need to use the edit date, but I wonder if users really care about when they changed a description or added a tag vs. when they initially decided to add the bookmark because it was of interest.

**Comment by sissbruecker** [comment]
Added a setting to switch between absolute / relative date formats as well as an option for hiding the date completely (=keep status quo).

**Relative**
- Displays "Today", "Yesterday" or weekday name for every date within the last 7 days
- After that displays how many weeks / months / years ago the bookmark was added

**Absolute**
- Displays "Today", "Yesterday" or weekday name for every date within the last 7 days (same as relative)
- After that displays a localized date format

Neither display the time as I thought that this is not really relevant.

**Comment by fs111** [comment]
@sissbruecker I pulled the latest image from dockerhub, but I am not seeing this new option. Do I have to run a migration for it to show up?

**Comment by sissbruecker** [comment]
@fs111 If you are using the Docker image you should be good, it runs migrations automatically as part of the start command. I pulled the image myself this morning and can confirm the setting is there. Just some sanity checks:
- Try a hard refresh in the browser - I sometimes have caching issues after an update
- Sure you also did create a new container after the pull?
- Spin up a temporary Docker container and check if the setting is there

**Comment by fs111** [comment]
@sissbruecker ah sorry. PEBKAC. My script to update everything was not recreating the container. Sorry for the noise. Works fine now!
